name: dio

description: |
homepage:
version: 5.0.3

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  http_parser:
   path: ./http_parser
  meta: ^1.5.0
  path: ^1.8.0

dev_dependencies:
  lints: any
  coverage: ^1.0.3
  crypto: ^3.0.2
